### PR TITLE
Remove screeps-server-mockup dependency

### PR DESCRIPTION
**Pull request by nsuthison**
Remove "screeps-server-mockup": "^1.4.3" since it has been deprecate, upgrade version of lodash since it has severity problem with version below 4.17.12

### CODE REVIEW

**Comment by thmsndk** [comment]
Fyi, screeps uses https://lodash.com/docs/3.10.1 and has it embedded / usable, i'd advise against updating the reference to lodash

**Comment by AlinaNova21** [comment]
Despite being marked deprecated, screeps-server-mockup it still works fine afaik. Its just not updated anymore.

**Comment by nsuthison** [comment]
@ags131 I remove screeps-server-mockup because it'll fail when you try to npm install or build.

@thmsndk I see, and it's not backward compatible also... but this severity is high and we should not look over it. Do screeps team has a plan to update this ?

**Comment by tcdejong** [comment]
@nsuthison The developers use lodash a lot in the engine so I don't expect them to upgrade it any time soon. No official word on it as far as I know. 

I do agree with removing screeps-server-mockup, it greatly expands the dependencies for the package, as it requires python 2 added to PATH on windows. That's awfully specific for features beginners aren't likely to use. Intermediates and above can install the package themselves.

**Comment by nsuthison** [comment]
Then, I'll remove update lodash version part for now.

**Comment by eduter** [comment]
Just saw the second person in the last few days showing up on #typescript channel, having problems with the starter kit because of Node >= 12, because of the dependencies of screeps-server-mockup. I'm sure there's more people having problems running the starter kit, than people actually using the mockup server. If you people still think it should be kept, it should at least be documented that the required version of Node is < 12. I've created a PR for this: #114

**Comment by eduter** [comment]
People keep having problems installing, because of this dependency (#118). This repo seems abandoned. Is there someone with write permission around to merge this PR? Is there any reason not to merge it?

**Comment by tcdejong** [comment]
It's a bit messy because the PR includes commits that are later reversed regarding lodash 4 / 3, as per the discussion above. But the net change is just removing the server mockup, which I'm all for. 

I'd say it should be merged.

**Comment by pyrodogg** [comment]
I'll take a look this weekend

**Comment by pyrodogg** [comment]
I agree that this should be removed for now since it's breaking critical new user experience. Will merge.

If screeps-server-mockup (or another mock server framework) is supported again in the future, it could be discussed to be brought back in to the starter template.

**Comment by MrMovl** [comment]
Not sure if this has to do with what you where talking about, but I just installed the node modules and npm audit is still mad at lodash:
```
                                                                                
# Run  npm install --save-dev lodash@4.17.15  to resolve 3 vulnerabilities
SEMVER WARNING: Recommended action is a potentially breaking change
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Low           │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ lodash                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ lodash [dev]                                                 │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ lodash                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/577                       │
└───────────────┴──────────────────────────────────────────────────────────────┘


┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ lodash                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ lodash [dev]                                                 │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ lodash                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/782                       │
└───────────────┴──────────────────────────────────────────────────────────────┘


┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ lodash                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ lodash [dev]                                                 │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ lodash                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/1065                      │

```

**Comment by pyrodogg** [comment]
No, it does not. Lodash version is pegged at 3.10.1 because that's the version the game engine uses. Until the Screeps developers update lodash, this library will stay at 3.10.1. 

I'll add a note to the README

**Pull request merged**
