### PR TITLE
Warning about using Steam client with gulp

### LINKED ISSUE #14: gulpfile.js is removed during gulp build
Hi, my gulpfile.js keeps getting deleted when I do the `npm run deploy` (or `gulp build`):

Console log of a full wipe and reclone:

https://files.slack.com/files-pri/T0HJCPP9T-F1W1334CR/full_wipe_and_reclone.txt

### PR DESCRIPTION
**Pull request by rickpelletier**
😢 Don't waste an entire afternoon trying to figure out why your project has lots of .js files and your gulpfile.js keeps getting deleted.

Resolves #14...

### CODE REVIEW

**Comment by rickpelletier** [comment]
:( man my git-fu is weak today

**Comment by valerian** [comment]
This is a very unusual case, I don't think it should have a dedicated warning (waiting for the opinion of other people to decide what to do)

**Comment by Dessix** [comment]
Maybe have the gulpfile detect if it's being run from the steam directory?

**Comment by valerian** [comment]
> Maybe have the gulpfile detect if it's being run from the steam directory?

Yeah good idea, it's quite easy to do

**Comment by resir014** [comment]
I agree with @valerian on this, this doesn't see the need of a dedicated warning, since a case where people would run this script from the Steam directory would be very minimal.

A better mitigation strategy would be to have the gulpfile detect the Steam directory and prevent the tasks from running (as per @Dessix).

I will be closing this and create an issue thread for it right now.

**Pull request closed without merging**
